// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataClass.Models
{
    [Table("Employee")]
    [Index("Email", Name = "UQ__Employee__A9D10534118354EE", IsUnique = true)]
    public partial class Employee
    {
        [Key]
        public int Id { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Name { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Email { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string MobileNumber { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string Gender { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Address { get; set; }
    }
}